/*
 * Created on 2025-01-24 ( 01:39:33 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.nus.sec.entities;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.*;

/**
 * JPA entity class for "TreeMenuTypeMstr"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="tree_menu_type_mstr", schema="public" )
public class TreeMenuTypeMstr implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="name", length=50)
    private String     name ;

    @JsonIgnore
    @Column(name="created_by")
    private Integer    createdBy ;

    @JsonIgnore
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on")
    private Date       createdOn ;

    @JsonIgnore
    @Column(name="updated_by")
    private Integer    updatedBy ;

    @JsonIgnore
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_on")
    private Date       updatedOn ;

    @Column(name="active_c", nullable=false, length=1)
    private String     activeC ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @JsonIgnore
    @OneToMany(mappedBy="treeMenuTypeMstr")
    private List<MenuManager> listOfMenuManager ; 

    @JsonIgnore
    @ManyToOne
    @JoinColumn(name="updated_by", referencedColumnName="id", insertable=false, updatable=false)
    private ApexUser   apexUser2 ; 

    @JsonIgnore
    @ManyToOne
    @JoinColumn(name="created_by", referencedColumnName="id", insertable=false, updatable=false)
    private ApexUser   apexUser ; 


    /**
     * Constructor
     */
    public TreeMenuTypeMstr() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setName( String name ) {
        this.name = name ;
    }
    public String getName() {
        return this.name;
    }

    public void setCreatedBy( Integer createdBy ) {
        this.createdBy = createdBy ;
    }
    public Integer getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedOn( Date createdOn ) {
        this.createdOn = createdOn ;
    }
    public Date getCreatedOn() {
        return this.createdOn;
    }

    public void setUpdatedBy( Integer updatedBy ) {
        this.updatedBy = updatedBy ;
    }
    public Integer getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedOn( Date updatedOn ) {
        this.updatedOn = updatedOn ;
    }
    public Date getUpdatedOn() {
        return this.updatedOn;
    }

    public void setActiveC( String activeC ) {
        this.activeC = activeC ;
    }
    public String getActiveC() {
        return this.activeC;
    }

    //--- GETTERS FOR LINKS
    public List<MenuManager> getListOfMenuManager() {
        return this.listOfMenuManager;
    } 

    public ApexUser getApexUser2() {
        return this.apexUser2;
    } 

    public ApexUser getApexUser() {
        return this.apexUser;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(createdBy);
        sb.append("|");
        sb.append(createdOn);
        sb.append("|");
        sb.append(updatedBy);
        sb.append("|");
        sb.append(updatedOn);
        sb.append("|");
        sb.append(activeC);
        return sb.toString(); 
    } 

}
