/*
 * Created on 2025-01-24 ( 01:39:32 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.nus.sec.entities;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.*;

/**
 * JPA entity class for "AccessRightsRbac"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="access_rights_rbac", schema="public" )
public class AccessRightsRbac implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="page_id")
    private Integer    pageId ;

    @Column(name="role_id")
    private Integer    roleId ;

    @JsonIgnore
    @Column(name="created_by")
    private Integer    createdBy ;

    @JsonIgnore
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on")
    private Date       createdOn ;

    @JsonIgnore
    @Column(name="modified_by")
    private Integer    modifiedBy ;

    @JsonIgnore
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modified_on")
    private Date       modifiedOn ;

    @Column(name="active_c", nullable=false, length=1)
    private String     activeC ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @JsonIgnore
    @ManyToOne
    @JoinColumn(name="modified_by", referencedColumnName="id", insertable=false, updatable=false)
    private ApexUser   apexUser2 ; 

    @JsonIgnore
    @ManyToOne
    @JoinColumn(name="page_id", referencedColumnName="id", insertable=false, updatable=false)
    private PageMstr   pageMstr ; 

    @JsonIgnore
    @ManyToOne
    @JoinColumn(name="role_id", referencedColumnName="id", insertable=false, updatable=false)
    private ApexRole   apexRole ; 

    @JsonIgnore
    @ManyToOne
    @JoinColumn(name="created_by", referencedColumnName="id", insertable=false, updatable=false)
    private ApexUser   apexUser ; 

    @JsonIgnore
    @OneToMany(mappedBy="accessRightsRbac")
    private List<OperationAccess> listOfOperationAccess ; 


    /**
     * Constructor
     */
    public AccessRightsRbac() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setPageId( Integer pageId ) {
        this.pageId = pageId ;
    }
    public Integer getPageId() {
        return this.pageId;
    }

    public void setRoleId( Integer roleId ) {
        this.roleId = roleId ;
    }
    public Integer getRoleId() {
        return this.roleId;
    }

    public void setCreatedBy( Integer createdBy ) {
        this.createdBy = createdBy ;
    }
    public Integer getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedOn( Date createdOn ) {
        this.createdOn = createdOn ;
    }
    public Date getCreatedOn() {
        return this.createdOn;
    }

    public void setModifiedBy( Integer modifiedBy ) {
        this.modifiedBy = modifiedBy ;
    }
    public Integer getModifiedBy() {
        return this.modifiedBy;
    }

    public void setModifiedOn( Date modifiedOn ) {
        this.modifiedOn = modifiedOn ;
    }
    public Date getModifiedOn() {
        return this.modifiedOn;
    }

    public void setActiveC( String activeC ) {
        this.activeC = activeC ;
    }
    public String getActiveC() {
        return this.activeC;
    }

    //--- GETTERS FOR LINKS
    public ApexUser getApexUser2() {
        return this.apexUser2;
    } 

    public PageMstr getPageMstr() {
        return this.pageMstr;
    } 

    public ApexRole getApexRole() {
        return this.apexRole;
    } 

    public ApexUser getApexUser() {
        return this.apexUser;
    } 

    public List<OperationAccess> getListOfOperationAccess() {
        return this.listOfOperationAccess;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(pageId);
        sb.append("|");
        sb.append(roleId);
        sb.append("|");
        sb.append(createdBy);
        sb.append("|");
        sb.append(createdOn);
        sb.append("|");
        sb.append(modifiedBy);
        sb.append("|");
        sb.append(modifiedOn);
        sb.append("|");
        sb.append(activeC);
        return sb.toString(); 
    } 

}
