/*
 * Created on 2025-01-30 ( 11:46:17 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.nus.fileupload.entities;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.nus.sec.entities.ApexUser;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * JPA entity class for "ProjectMonthlyResourceAttrition"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="project_monthly_resource_attrition", schema="public" )
public class ProjectMonthlyResourceAttrition implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="emp_code", nullable=false, length=2147483647)
    private String     empCode ;

    @Column(name="emp_status", length=100)
    private String     empStatus ;

    @Column(name="project_code_id", nullable=false)
    private Integer    projectCodeId ;

    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy")
    @Temporal(TemporalType.DATE)
    @Column(name="file_upload_date")
    private Date    fileUploadDate ;

    @Column(name="emp_name", length=100)
    private String     empName ;

   

    @Column(name="dept_name", length=100)
    private String     deptName ;

    @JsonIgnore
    @Column(name="created_by")
    private Integer    createdBy ;

    @Column(name="designation", length=100)
    private String     designation ;

    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy")
    @Temporal(TemporalType.DATE)
    @Column(name="doj")
    private Date       doj ;

    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy")
    @JsonIgnore
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on")
    private Date       createdOn ;

    @JsonIgnore
    @Column(name="modified_by")
    private Integer    modifiedBy ;

    @Column(name="reportin_manager", length=100)
    private String     reportinManager ;

    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy")
    @JsonIgnore
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modified_on")
    private Date    modifiedOn ;

    @Column(name="work_location", length=100)
    private String     workLocation ;

    @Column(name="employement_status", length=100)
    private String     employementStatus ;

    @JsonIgnore
    @Column(name="active_c", nullable=false, length=1)
    private String     activeC ;

    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy")
    @Temporal(TemporalType.DATE)
    @Column(name="lwd")
    private Date       lwd ;

    @Column(name="unit", length=100)
    private String     unit ;

    @Column(name="attrition_type", nullable=false, length=50)
    private String     attritionType ;

    @Column(name="file_reference_id")
    private Integer    fileReferenceId ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @JsonIgnore
    @ManyToOne
    @JoinColumn(name="modified_by", referencedColumnName="id", insertable=false, updatable=false)
    private ApexUser   apexUser2 ; 

    @JsonIgnore
    @ManyToOne
    @JoinColumn(name="file_reference_id", referencedColumnName="id", insertable=false, updatable=false)
    private FileReference fileReference ; 

    @JsonIgnore
    @ManyToOne
    @JoinColumn(name="created_by", referencedColumnName="id", insertable=false, updatable=false)
    private ApexUser   apexUser ; 


    /**
     * Constructor
     */
    public ProjectMonthlyResourceAttrition() {
		super();
    }
    
    public ProjectMonthlyResourceAttrition(Date fileUploadDate, int userId, Date date, String activeC) {
		this.fileUploadDate = fileUploadDate;		
		this.createdBy = userId;
		this.createdOn = new Date();
		this.activeC = activeC;
	}
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setEmpCode( String empCode ) {
        this.empCode = empCode ;
    }
    public String getEmpCode() {
        return this.empCode;
    }

    public void setEmpStatus( String empStatus ) {
        this.empStatus = empStatus ;
    }
    public String getEmpStatus() {
        return this.empStatus;
    }

    public void setProjectCodeId( Integer projectCodeId ) {
        this.projectCodeId = projectCodeId ;
    }
    public Integer getProjectCodeId() {
        return this.projectCodeId;
    }

  

    public void setEmpName( String empName ) {
        this.empName = empName ;
    }
    public String getEmpName() {
        return this.empName;
    }

    

   

	public Date getFileUploadDate() {
		return fileUploadDate;
	}

	public void setFileUploadDate(Date fileUploadDate) {
		this.fileUploadDate = fileUploadDate;
	}

	public void setDeptName( String deptName ) {
        this.deptName = deptName ;
    }
    public String getDeptName() {
        return this.deptName;
    }

    public void setCreatedBy( Integer createdBy ) {
        this.createdBy = createdBy ;
    }
    public Integer getCreatedBy() {
        return this.createdBy;
    }

    public void setDesignation( String designation ) {
        this.designation = designation ;
    }
    public String getDesignation() {
        return this.designation;
    }

    public void setDoj( Date doj ) {
        this.doj = doj ;
    }
    public Date getDoj() {
        return this.doj;
    }

    public void setCreatedOn( Date createdOn ) {
        this.createdOn = createdOn ;
    }
    public Date getCreatedOn() {
        return this.createdOn;
    }

    public void setModifiedBy( Integer modifiedBy ) {
        this.modifiedBy = modifiedBy ;
    }
    public Integer getModifiedBy() {
        return this.modifiedBy;
    }

    public void setReportinManager( String reportinManager ) {
        this.reportinManager = reportinManager ;
    }
    public String getReportinManager() {
        return this.reportinManager;
    }

    public void setModifiedOn( Date modifiedOn ) {
        this.modifiedOn = modifiedOn ;
    }
    public Date getModifiedOn() {
        return this.modifiedOn;
    }

    public void setWorkLocation( String workLocation ) {
        this.workLocation = workLocation ;
    }
    public String getWorkLocation() {
        return this.workLocation;
    }

    public void setEmployementStatus( String employementStatus ) {
        this.employementStatus = employementStatus ;
    }
    public String getEmployementStatus() {
        return this.employementStatus;
    }

    public void setActiveC( String activeC ) {
        this.activeC = activeC ;
    }
    public String getActiveC() {
        return this.activeC;
    }

    public void setLwd( Date lwd ) {
        this.lwd = lwd ;
    }
    public Date getLwd() {
        return this.lwd;
    }

    public void setUnit( String unit ) {
        this.unit = unit ;
    }
    public String getUnit() {
        return this.unit;
    }

    public void setAttritionType( String attritionType ) {
        this.attritionType = attritionType ;
    }
    public String getAttritionType() {
        return this.attritionType;
    }

    public void setFileReferenceId( Integer fileReferenceId ) {
        this.fileReferenceId = fileReferenceId ;
    }
    public Integer getFileReferenceId() {
        return this.fileReferenceId;
    }

    //--- GETTERS FOR LINKS
    public ApexUser getApexUser2() {
        return this.apexUser2;
    } 

    public FileReference getFileReference() {
        return this.fileReference;
    } 

    public ApexUser getApexUser() {
        return this.apexUser;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(empCode);
        sb.append("|");
        sb.append(empStatus);
        sb.append("|");
        sb.append(projectCodeId);
        
        sb.append("|");
        sb.append(empName);
        
        sb.append("|");
        sb.append(deptName);
        sb.append("|");
        sb.append(createdBy);
        sb.append("|");
        sb.append(designation);
        sb.append("|");
        sb.append(doj);
        sb.append("|");
        sb.append(createdOn);
        sb.append("|");
        sb.append(modifiedBy);
        sb.append("|");
        sb.append(reportinManager);
        sb.append("|");
        sb.append(modifiedOn);
        sb.append("|");
        sb.append(workLocation);
        sb.append("|");
        sb.append(employementStatus);
        sb.append("|");
        sb.append(activeC);
        sb.append("|");
        sb.append(lwd);
        sb.append("|");
        sb.append(unit);
        sb.append("|");
        sb.append(attritionType);
        sb.append("|");
        sb.append(fileReferenceId);
        return sb.toString(); 
    } 

}
