/*
 * Created on 2025-01-30 ( 11:46:17 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.nus.fileupload.entities;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.nus.sec.entities.ApexUser;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * JPA entity class for "ProjectMonthlyResourceUtilization"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="project_monthly_resource_utilization", schema="public" )
public class ProjectMonthlyResourceUtilization implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="billed_days", nullable=false)
    private Double    billedDays ;

    @Column(name="available_days", nullable=false)
    private Double    availableDays ;

    @Column(name="project_code_id", nullable=false)
    private Integer    projectCodeId ;

    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy")
    @Temporal(TemporalType.DATE)
    @Column(name="file_upload_date")
    private Date    fileUploadDate ;

    @JsonIgnore
    @Column(name="created_by")
    private Integer    createdBy ;

    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy")
    @JsonIgnore
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on")
    private Date       createdOn ;

    @JsonIgnore
    @Column(name="modified_by")
    private Integer    modifiedBy ;

    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy")
    @JsonIgnore
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modified_on")
    private Date       modifiedOn ;

    @JsonIgnore
    @Column(name="active_c", nullable=false, length=1)
    private String     activeC ;

    
    @Column(name="file_reference_id")
    private Integer    fileReferenceId ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @JsonIgnore
    @ManyToOne
    @JoinColumn(name="file_reference_id", referencedColumnName="id", insertable=false, updatable=false)
    private FileReference fileReference ; 

    @JsonIgnore
    @ManyToOne
    @JoinColumn(name="created_by", referencedColumnName="id", insertable=false, updatable=false)
    private ApexUser   apexUser ; 

    @JsonIgnore
    @ManyToOne
    @JoinColumn(name="modified_by", referencedColumnName="id", insertable=false, updatable=false)
    private ApexUser   apexUser2 ; 


    /**
     * Constructor
     */
    public ProjectMonthlyResourceUtilization() {
		super();
    }
    
    public ProjectMonthlyResourceUtilization(Date fileUploadDate, int userId, Date date, String activeC) {
		this.fileUploadDate = fileUploadDate;		
		this.createdBy = userId;
		this.activeC = activeC;		
		this.createdOn = new Date();
	}
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setBilledDays( Double billedDays ) {
        this.billedDays = billedDays ;
    }
    public Double getBilledDays() {
        return this.billedDays;
    }

    public void setAvailableDays( Double availableDays ) {
        this.availableDays = availableDays ;
    }
    public Double getAvailableDays() {
        return this.availableDays;
    }

    public void setProjectCodeId( Integer projectCodeId ) {
        this.projectCodeId = projectCodeId ;
    }
    public Integer getProjectCodeId() {
        return this.projectCodeId;
    }

   

    public Date getFileUploadDate() {
		return fileUploadDate;
	}

	public void setFileUploadDate(Date fileUploadDate) {
		this.fileUploadDate = fileUploadDate;
	}

	public void setCreatedBy( Integer createdBy ) {
        this.createdBy = createdBy ;
    }
    public Integer getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedOn( Date createdOn ) {
        this.createdOn = createdOn ;
    }
    public Date getCreatedOn() {
        return this.createdOn;
    }

    public void setModifiedBy( Integer modifiedBy ) {
        this.modifiedBy = modifiedBy ;
    }
    public Integer getModifiedBy() {
        return this.modifiedBy;
    }

    public void setModifiedOn( Date modifiedOn ) {
        this.modifiedOn = modifiedOn ;
    }
    public Date getModifiedOn() {
        return this.modifiedOn;
    }

    public void setActiveC( String activeC ) {
        this.activeC = activeC ;
    }
    public String getActiveC() {
        return this.activeC;
    }

    public void setFileReferenceId( Integer fileReferenceId ) {
        this.fileReferenceId = fileReferenceId ;
    }
    public Integer getFileReferenceId() {
        return this.fileReferenceId;
    }

    //--- GETTERS FOR LINKS
    public FileReference getFileReference() {
        return this.fileReference;
    } 

    public ApexUser getApexUser() {
        return this.apexUser;
    } 

    public ApexUser getApexUser2() {
        return this.apexUser2;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(billedDays);
        sb.append("|");
        sb.append(availableDays);
        sb.append("|");
        sb.append(projectCodeId);
        sb.append("|");
        sb.append(fileUploadDate);
       
        sb.append("|");
        sb.append(createdBy);
        sb.append("|");
        sb.append(createdOn);
        sb.append("|");
        sb.append(modifiedBy);
        sb.append("|");
        sb.append(modifiedOn);
        sb.append("|");
        sb.append(activeC);
        sb.append("|");
        sb.append(fileReferenceId);
        return sb.toString(); 
    } 

}
