/*
 * Created on 2025-01-24 ( 01:39:32 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.nus.pvt.admin.entities;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.nus.sec.entities.ApexUser;

import jakarta.persistence.*;

/**
 * JPA entity class for "AssignPracticeProjectToMgmt"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="assign_practice_project_to_mgmt", schema="public" )
public class AssignPracticeProjectToMgmt implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="assigned_project_practice_id")
    private Integer    assignedProjectPracticeId ;

    @Column(name="management_user_id")
    private Integer    managementUserId ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="assigned_on")
    private Date       assignedOn ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="released_on")
    private Date       releasedOn ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="closed_on")
    private Date       closedOn ;

    @JsonIgnore
    @Column(name="created_by")
    private Integer    createdBy ;

    @JsonIgnore
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on")
    private Date       createdOn ;

    @JsonIgnore
    @Column(name="modified_by")
    private Integer    modifiedBy ;

    @Column(name="active_c", nullable=false, length=1)
    private String     activeC ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @JsonIgnore
    @ManyToOne
    @JoinColumn(name="created_by", referencedColumnName="id", insertable=false, updatable=false)
    private ApexUser   apexUser ; 

    @JsonIgnore
    @ManyToOne
    @JoinColumn(name="modified_by", referencedColumnName="id", insertable=false, updatable=false)
    private ApexUser   apexUser2 ; 

    @JsonIgnore
    @ManyToOne
    @JoinColumn(name="assigned_project_practice_id", referencedColumnName="id", insertable=false, updatable=false)
    private AssignDmProjectToPractice assignDmProjectToPractice ; 


    /**
     * Constructor
     */
    public AssignPracticeProjectToMgmt() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setAssignedProjectPracticeId( Integer assignedProjectPracticeId ) {
        this.assignedProjectPracticeId = assignedProjectPracticeId ;
    }
    public Integer getAssignedProjectPracticeId() {
        return this.assignedProjectPracticeId;
    }

    public void setManagementUserId( Integer managementUserId ) {
        this.managementUserId = managementUserId ;
    }
    public Integer getManagementUserId() {
        return this.managementUserId;
    }

    public void setAssignedOn( Date assignedOn ) {
        this.assignedOn = assignedOn ;
    }
    public Date getAssignedOn() {
        return this.assignedOn;
    }

    public void setReleasedOn( Date releasedOn ) {
        this.releasedOn = releasedOn ;
    }
    public Date getReleasedOn() {
        return this.releasedOn;
    }

    public void setClosedOn( Date closedOn ) {
        this.closedOn = closedOn ;
    }
    public Date getClosedOn() {
        return this.closedOn;
    }

    public void setCreatedBy( Integer createdBy ) {
        this.createdBy = createdBy ;
    }
    public Integer getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedOn( Date createdOn ) {
        this.createdOn = createdOn ;
    }
    public Date getCreatedOn() {
        return this.createdOn;
    }

    public void setModifiedBy( Integer modifiedBy ) {
        this.modifiedBy = modifiedBy ;
    }
    public Integer getModifiedBy() {
        return this.modifiedBy;
    }

    public void setActiveC( String activeC ) {
        this.activeC = activeC ;
    }
    public String getActiveC() {
        return this.activeC;
    }

    //--- GETTERS FOR LINKS
    public ApexUser getApexUser() {
        return this.apexUser;
    } 

    public ApexUser getApexUser2() {
        return this.apexUser2;
    } 

    public AssignDmProjectToPractice getAssignDmProjectToPractice() {
        return this.assignDmProjectToPractice;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(assignedProjectPracticeId);
        sb.append("|");
        sb.append(managementUserId);
        sb.append("|");
        sb.append(assignedOn);
        sb.append("|");
        sb.append(releasedOn);
        sb.append("|");
        sb.append(closedOn);
        sb.append("|");
        sb.append(createdBy);
        sb.append("|");
        sb.append(createdOn);
        sb.append("|");
        sb.append(modifiedBy);
        sb.append("|");
        sb.append(activeC);
        return sb.toString(); 
    } 

}
